shared_buffers = 128MB
min_wal_size = 1GB
max_wal_size = 2880MB
maintenance_work_mem = 256MB
max_connections = 100
temp_buffers = 32MB
work_mem = 32MB
wal_buffers = 1024kB
wal_writer_delay = 500ms
random_page_cost = 1.1
track_activity_query_size = 16384
autovacuum = on
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
jit = off
